---
homebrew_cask_packages:
    - google-chrome
    - firefox
    - flux
    - virtualbox
    - vagrant
    - evernote
    - spotify
    - sourcetree
    - lightpaper
    - integrity
    - skype
    - xquartz
    - iterm2

homebrew_packages:
    - wget
    - tree
    - vim
      #- ack
    - git
      #- rbenv
      #- ruby-build
      #- elasticsearch
    - mysql
    - tmux
    - tree
    - nmap
    - mtr
    - iftop
    - pv
    - python
    - coreutils
    - dos2unix
    - ctags
    - ssh-copy-id
    - jq
