- name: Install libraries with homebrew
  homebrew: name={{ item }} state=present
  with_items:
    - wget
    - tree
    - vim
      #- ack
    - git
      #- rbenv
      #- ruby-build
      #- elasticsearch
    - mysql
    - tmux
    - tree
    - nmap
    - mtr
    - iftop
    - pv
    - python
    - coreutils
    - dos2unix
    - ctags
    - ssh-copy-id

vars:
  applications:
    - google-chrome
    - firefox
    - flux
    - virtualbox
    - vagrant
    - evernote
    - spotify
    - sourcetree
    - lightpaper
    - integrity
    - skype
    - xquartz


tasks:
  - name: Check for installed apps(casks)
    shell: brew cask list | grep {{ item }}
    register: installed_applications
    with_items: applications
    ignore_errors: true

  - name: Install apps with brew-cask
    shell: brew cask install {{ item }}
    with_items: applications
    when: "{{ item not in installed_applications.results|map(attribute='stdout') }}"

