- name: Set OSX screen saver settings
  command: "{{ item }}"
  with_items:
    - defaults -currentHost write com.apple.screensaver idleTime 600
    - defaults write com.apple.screensaver askForPassword -int 1
    - defaults write com.apple.screensaver askForPasswordDelay -int 0

- name: Set OSX set fast key repeat rate
  command: "{{ item }}"
  with_items:
    - defaults write -g InitialKeyRepeat -int 25
    - defaults write -g KeyRepeat -int 2

- name: Disable creating .DS_Store files on network shares
  command: defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

- name: "Privacy: Don't send Safari search queries to Apple"
  command: "{{ item }}"
  with_items:
    - defaults write com.apple.Safari UniversalSearchEnabled -bool false
    - defaults write com.apple.Safari SuppressSearchSuggestions -bool true

- name: Setup Web Inspector for Safari
  command: "{{ item }}"
  with_items:
    - defaults write com.apple.Safari IncludeDevelopMenu -bool true
    - defaults write com.apple.Safari WebKitDeveloperExtrasEnabledPreferenceKey -bool true
    - defaults write com.apple.Safari "com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled" -bool true
    - defaults write NSGlobalDomain WebKitDeveloperExtras -bool true

- name: Disable sending Spotlight search results to Apple
  command: "{{ item }}"
  ignore_errors: true
  with_items:
    - defaults write com.apple.spotlight orderedItems -array \
        '{"enabled" = 1;"name" = "APPLICATIONS";}' \
        '{"enabled" = 1;"name" = "SYSTEM_PREFS";}' \
        '{"enabled" = 1;"name" = "DIRECTORIES";}' \
        '{"enabled" = 1;"name" = "PDF";}' \
        '{"enabled" = 1;"name" = "FONTS";}' \
        '{"enabled" = 0;"name" = "DOCUMENTS";}' \
        '{"enabled" = 0;"name" = "MESSAGES";}' \
        '{"enabled" = 0;"name" = "CONTACT";}' \
        '{"enabled" = 0;"name" = "EVENT_TODO";}' \
        '{"enabled" = 0;"name" = "IMAGES";}' \
        '{"enabled" = 0;"name" = "BOOKMARKS";}' \
        '{"enabled" = 0;"name" = "MUSIC";}' \
        '{"enabled" = 0;"name" = "MOVIES";}' \
        '{"enabled" = 0;"name" = "PRESENTATIONS";}' \
        '{"enabled" = 0;"name" = "SPREADSHEETS";}' \
        '{"enabled" = 0;"name" = "SOURCE";}' \
        '{"enabled" = 0;"name" = "MENU_DEFINITION";}' \
        '{"enabled" = 0;"name" = "MENU_OTHER";}' \
        '{"enabled" = 0;"name" = "MENU_CONVERSION";}' \
        '{"enabled" = 0;"name" = "MENU_EXPRESSION";}' \
        '{"enabled" = 0;"name" = "MENU_WEBSEARCH";}' \
        '{"enabled" = 0;"name" = "MENU_SPOTLIGHT_SUGGESTIONS";}'
      # Load new settings before rebuilding the index
    -  killall mds > /dev/null 2>&1
      # Make sure indexing is enabled for the main volume
    - sudo mdutil -i on / > /dev/null
      # Rebuild the index from scratch
    - sudo mdutil -E / > /dev/null

- name: "Automatically quit printer app once the print jobs complete"
  command: defaults write com.apple.print.PrintingPrefs "Quit When Finished" -bool true

- name: "Disable spotlight from indexing new mounted /Volumes"
  command: sudo defaults write /.Spotlight-V100/VolumeConfiguration Exclusions -array "/Volumes"
